import { Inter } from "next/font/google";
import "../globals.css";
import Provider from "@components/Provider";
import NavBar from "@components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-2  h-[100vh] overflow-hidden`}>
        <Provider>
            <NavBar />
            {children}
        </Provider>
      </body>
    </html>
  );
}
